#!/bin/sh
# mass mv

# print to stderr
err() {
	echo "error: $1" >&2
}

# check if line count is the same
cmplc() {
	[ "$(wc -l <"$1")" = "$(wc -l <"$2")" ]
}

# on-exit cleanup
cleanup() {
	rm -rf "$tmp"
}

# perform renaming
rename() {
	while read -r old && read -r new; do
		[ "$old" != "$new" ] || continue
		mv -i "$old" "$new"
	done
}

[ $# -gt 0 ] || {
	echo "usage: ${0##*/} FILES..."
	exit
}
[ "$EDITOR" ] || {
	err 'EDITOR variable is not set'
	exit 1
}
tmp=$(mktemp -d /tmp/mmvXXX) || {
	err 'failed to create temporary directory'
	exit 1
}
trap cleanup EXIT
printf '%s\n' "$@" | tee "$tmp/old" >"$tmp/new"
$EDITOR "$tmp/new" || {
	err "$EDITOR terminated with code $?"
	exit 1
}
cmplc "$tmp/old" "$tmp/new" || {
	err 'different line count'
	exit 1
}
paste -d '\n' "$tmp/old" "$tmp/new" | rename
