#!/bin/sh
# News viewer for sfeed.

# sfeed data directory
sfeedpath=~/.sfeed

# get (and possibly update) last access time
since() {
	cd "$sfeedpath" || exit
	if [ $# -gt 0 ]; then
		date -d"$*" +%s
	else
		stat -c%X last
		touch last
	fi
}

# list feeds younger than $1 sorted by time
newfeeds() {
	cd "$sfeedpath/feeds" || exit
	ls |
		xargs -rd '\n' awk -v "last=$1" '{
			if ($1 > last)
				print FILENAME "\t" $0
			else
				nextfile
		}' |
		sort -t '	' -k2nr,2
}

# format feeds
feedfmt() {
	awk -F '\t' '{
		feed = sprintf("%-20.20s", $1)
		date = strftime("%Y %b %d %H:%M:%S", $2)
		title = sprintf("%-40.40s", $3)
		link = $4
		printf("%s  %s  %s  %s\n", feed, date, title, link)
	}'
}

# open selected feeds in the browser
last=$(since "$@")
newfeeds "$last" |
	feedfmt |
	dmenu -i -l 10 -p "Since $(date -d "@$last" +'%Y %b %d %H:%M:%S')" |
	awk '{print $NF}' |
	xargs -rd'\n' firefox
